#+ endpoint: https://api.krr.triply.cc/datasets/mkumpel/FruitCuttingKG/services/FoodCuttingKG/sparql

#+ summary: Query for extracting the tool for cutting the specific food object
#+ tags: 
#+ - tool

# Query for extracting the tool for cutting the specific food object
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX soma: <http://www.ease-crc.org/ont/SOMA.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cut2: <http://www.ease-crc.org/ont/situation_awareness#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foodon: <http://purl.obolibrary.org/obo/>
PREFIX dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
SELECT ?whattool WHERE {
  ?_food rdfs:subClassOf ?node.
  ?node owl:onProperty soma:hasDisposition.
  ?node owl:someValuesFrom ?collection.
  ?collection owl:intersectionOf ?node2.
  ?node2 rdf:first cut2:Cuttability.
  ?node2 rdf:rest ?toolnode.
  ?toolnode rdf:rest ?collection2.
  ?collection2 rdf:first ?tooluse.
  ?tooluse owl:onProperty soma:affordsTrigger.
  ?tooluse owl:allValuesFrom ?tool.
  ?tool owl:onProperty dul:classifies.
  ?tool owl:allValuesFrom ?whattool.
}
